image: python:3.5

stages:
- test

before_script:
    - pip install -r requirements.txt
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r test-requirements.txt
    - pip install wheel
    - python setup.py develop
    
coverage:
    stage: test
    script:
        - nosetests -s MIGDataCollector --with-coverage --cover-erase --cover-inclusive --cover-package=MIGDataCollector --cover-html
        - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
        paths:
            - MIGDataCollector
        expire_in: 1 day