image: python:3.5

stages:
- test

#Production stage
production:   
   stage: test   
   before_script: 
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_SERVER_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
   script:
      - ssh -t devops@$DEPLOY_SERVER "cd /opt && sh tesh.sh" 
   environment:     
      name: test 
   when: manual