image: python:3.5

stages:
- test

#Production stage
production:   
   stage: test   
   before_script: 
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $$DEPLOY_SERVER >> ~/.ssh/known_hosts  
   script:     
      - ip a
      - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd /opt && sh tesh.sh" 
   environment:     
      name: test 
   when: manual