image: python:3.5

stages:
- test
- build

before_script:
    - pip install -r requirements.txt
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r test-requirements.txt
    - pip install wheel
    - python setup.py develop
    
coverage:
    stage: test
    script:
        - sh version.sh
        - nosetests -s MIGDataCollector --with-coverage --cover-erase --cover-inclusive --cover-package=MIGDataCollector --cover-html
    only:
        - branches
        
    except:
        - master
        
wheel:
    stage: build
    script:
        - sh version.sh
        - nosetests -s MIGDataCollector --with-coverage --cover-erase --cover-inclusive --cover-package=MIGDataCollector --cover-html
        - python setup.py bdist_wheel
    artifacts:
       paths:
          - dist/
    only:
        - master
