image: python:3.5

stages:
- test
- deploy

before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python setup.py develop

runTest:
    stage: test
    script:
        - export PYTHONPATH=/builds/Hariharan/gitlabci
        - nosetests -sx

coverage:
    stage: test
    script:
        - export PYTHONPATH=/builds/Hariharan/gitlabci
        - nosetests -c .noserc -q --cover-html-dir=build --cover-html
        - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
        paths:
            - build
        expire_in: 1 day

apidoc:
    stage: test
    script:
        - cd MIGDataCollector
        - fab make
    artifacts:
        paths:
            - MIGDataCollector/build/html
        expire_in: 1 day

pages:
    stage: deploy
    before_script:
        - "true"
    script:
        - mkdir -p public/coverage
        - cp -fr MIGDataCollector/build/html/* public/
        - cp -fr build/* public/coverage/
    dependencies:
        - coverage
        - apidoc
    artifacts:
        paths:
            - public
