test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r test-requirements.txt
  - apt-get install python3-setuptools
  - python3 setup.py develop
  - nosetests -s MIGDataCollector --with-coverage --cover-erase --cover-inclusive --cover-package=MIGDataCollector --cover-xml --with-xunit > nose_test.out
  only:
    - branches
wheel:
  script: python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/