image: python:3.5

stages:
- test

before_script:
    - cd /builds/Hariharan/gitlabci
    - ls -la
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - apt-get install -y mailutils
    - apt-get install -y mutt
    - echo 'This is the body of the email' | mail -s 'test' s.hariharan@mcwaneindia.com
    - python test.py

coverage:
    stage: test
    script:
          - python --version