image: docker:latest

services:
- docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

stages:
  - build

build:
  stage: build
  script:
    - $(aws ec2-13-126-134-252.ap-south-1.compute.amazonaws.com get-login --no-include-email --region ap-south-1)
    - ls