image: python:3.5

test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r test-requirements.txt
  - pip install wheel
  - python setup.py develop
  - nosetests -s MIGDataCollector --with-coverage --cover-erase --cover-inclusive --cover-package=MIGDataCollector --cover-xml --with-xunit > nose_test.out
  - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/
  only:
    - branches
    - merge-requests
