image: python:3.5

stages:
- test
- build

before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r test-requirements.txt
    - python setup.py develop

coverage:
    stage: test
    script:
        - nosetests -s MIGDataCollector --with-coverage --cover-erase --cover-inclusive --cover-package=MIGDataCollector --cover-html
        - nosetests -c .noserc -q --cover-html-dir=build --cover-html
    artifacts:
        paths:
            - build
     only:
        - branches
        
    except:
        - master
        
wheel:
    stage: build
    script:
        - python setup.py bdist_wheel
       
    artifacts:
       paths:
          - dist/
    only:
        - master

