image: python:3.5

stages:
- test

#Production stage
production:   
   stage: test   
   before_script: 
     - mkdir -p ~/.ssh     
     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
     - chmod 600 ~/.ssh/id_rsa     
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   script:
      - ssh ubuntu@$DEPLOY_SERVER "cd /opt && sh tesh.sh" 
   environment:     
      name: test 
   when: manual